[package]
name = "day11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io = { path = "../io" }

[[bin]]
name = "day11a"
path = "src/a.rs"

[[bin]]
name = "day11b"
path = "src/b.rs"