[package]
name = "day8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io = { path = "../io" }

[[bin]]
name = "day8a"
path = "src/a.rs"

[[bin]]
name = "day8b"
path = "src/b.rs"